#ifndef __P_CLOCK_H__
#define __P_CLOCK_H__

#define PLATFORM_CLOCK_BASE 0x7E00B000

#define PLATFORM_CLOCK_LOAD 0x400
#define PLATFORM_CLOCK_CONTROL 0x408
#define PLATFORM_CLOCK_IRQACK 0x40C
#define PLATFORM_CLOCK_RELOAD 0x418
#define PLATFORM_CLOCK_PREDIV 0x41C

#endif