#ifndef __P_BUS_H__
#define __P_BUS_H__

#define PLATFORM_BUS_BASE 0x7E000000
#define PLATFORM_BUS_PHYS_BASE 0x20000000

#define PLATFORM_BUS_TO_PHYS(u) ((u-PLATFORM_BUS_BASE)+PLATFORM_BUS_PHYS_BASE)

#endif